from fastapi import APIRouter
from app.api import auth, tasks, completions, categories, stats, projects, members, board, notifications, notebook, calendar, users, access_requests, sprints, performance, ai, comments, activity, watchers, search, friends, push, ical, quick_tasks

api_router = APIRouter()

api_router.include_router(auth.router)
api_router.include_router(access_requests.router)
api_router.include_router(quick_tasks.router)
api_router.include_router(users.router)
api_router.include_router(tasks.router)
api_router.include_router(completions.router)
api_router.include_router(categories.router)
api_router.include_router(stats.router)
api_router.include_router(projects.router)
api_router.include_router(members.router)
api_router.include_router(board.router)
api_router.include_router(sprints.router)
api_router.include_router(sprints.backlog_router)
api_router.include_router(performance.router)
api_router.include_router(ai.router)
api_router.include_router(notifications.router)
api_router.include_router(notebook.router)
api_router.include_router(calendar.router)
api_router.include_router(comments.router)
api_router.include_router(activity.router)
api_router.include_router(watchers.router)
api_router.include_router(search.router)
api_router.include_router(friends.router)
api_router.include_router(push.router)
api_router.include_router(ical.router)
